<?xml version="1.0"?>
<robot name="twr" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="inertia.macro.xacro"/>
    <xacro:include filename="colors.xacro"/>

    <xacro:property name="base_length" value="0.7"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.1"/>

    <xacro:property name="wheel_radius" value="0.2"/>
    <xacro:property name="wheel_width" value="0.01"/>

    <!-- === WORLD === -->
    <link name="world_link"/>

    <!-- === BASE === -->
    <joint name="base_joint" type="fixed">
        <parent link="world_link"/>
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="1" l="${base_length}" w="${base_width}"  h="${base_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:box_inertia>
    </link>

    <!-- === WHEELS === -->
    <!-- <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link" />
        <origin xyz="0 ${base_width/2 + wheel_width/2 + 0.01} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertia m="1" r="${wheel_radius}" l="${wheel_width}">
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </xacro:cylinder_inertia>
    </link> -->


</robot>
